### ISSUE TITLE
Problem with running base64 command twice

### ISSUE THREAD

**Issue by qlmradoszewski** [cameronjust/TA-base64#1]
When running the 2.0.1 version of the app, using base64 command with action="decode" and mode="replace", I have ran into an issue where when I try to use base64 command in my searches more than once the search never ends. (I want to decode two different fields in the same search). The command works fine for both of these fields separately.

I have also noticed that when I stop the search manually it cannot finalize as well so I had to delete the jobs that were already running, rollback to the previous version of the app which unfortunately does not support the padding fix and backfill the data (I am using it as a part of search that is collecting the data to a summary index). That typically indicates that there is a loop in the script that never ends or a resource blocked by the first command but I can't really debug it on my own.
As of now I am running the old version of the app as I have a workaround for the lack of padding fix - I am adding it manually to the field using eval command and then stripping the padding after the conversion but it would be really nice not to have to do that every time I want to run the command, especially that there are more Splunk users and some of them are unaware of the problem which leads to incomplete results and a script error shown in Splunk UI.

I'd really appreciate fixing this problem and can provide help with the issue replication if needed.

**Comment by cameronjust** [comment]
Did you try this it seems to work for a multiple values?

| makeresults 
| eval encodedField = "ZnJlZA==", otherEncodedField="YmFycnkK" 
| base64 action=decode field=encodedField mode=append 
| eval encodedField_decoded = base64
| base64 action=decode field=otherEncodedField mode=append 
| eval otherEncodedField_decoded = base64
| eval toEncode = "this is to be encoded"
| base64 action=encode field=toEncode mode=append
| table _time encodedField* otherEncodedField* *

Regardless I'm updating it now to include the latest splunklib so check back in a few hours for an updated version.

I'm also changing it so instead of creating a field called base64 it just uses the original fieldname with _base64 added to the end so the above example would be simplified to

| makeresults 
| eval encodedField = "ZnJlZA==", otherEncodedField="YmFycnkK" 
| base64 action=decode field=encodedField mode=append 
| base64 action=decode field=otherEncodedField mode=append 
| eval toEncode = "this is to be encoded"
| base64 action=encode field=toEncode mode=append
| table _time encodedField* otherEncodedField* *

**Comment by cameronjust** [comment]
As for the loop getting blocked I'm not sure what is happening there. Hopefully the latest splunklib fixes that.

**Comment by qlmradoszewski** [comment]
Thank you so much for for updating to the latest splunklib @cameronjust! New version works without any issues and solves the problem for me!

It may be that the issue I ran into is only present in newer versions of Splunk (I am running Splunk 8.1.4 here). For anyone experiencing same issues - updating to the newest version solves it for 8.1.4
